#ifndef XC_MISC_CH_
#define XC_MISC_CH_

#define XCB_XCMISC_MAJOR_VERSION  1
#define XCB_XCMISC_MINOR_VERSION  1
#define XCB_XC_MISC_GET_VERSION   0
#define XCB_XC_MISC_GET_XID_RANGE 1
#define XCB_XC_MISC_GET_XID_LIST  2

#endif /* XC_MISC_CH_ */
